### ISSUE TITLE
Doesnt work with slide toggle

### ISSUE THREAD

**Issue by KingSora** [baijunjie/jquery.animate#2]
Cant use $(element).slideToggle(500) with this lib.
This library is really cool, I'd like it to use it...

I hope you can fix this, because this function is really important! :)

Best regards,
Sora

**Comment by KingSora** [comment]
I Think the same affects the function "$(element).fadeToggle(500). Please have a look

**Comment by baijunjie** [comment]
You are right, I have been in 1.6.9 fix the problem.

**Comment by KingSora** [comment]
You're great! Thank you very much :)
