### ISSUE TITLE
Can we have "inProgress" function to be called during animation?

### ISSUE THREAD

**Issue by alex00zoe** [baijunjie/jquery.animate#5]
If the `inProgress`could be called at a rate of `fps 24` (for example) during animation, would be great! 

This will open door to a new world!

Thanks a lot!

**Comment by alex00zoe** [comment]
meanwhile, can we access the current `animatedValue`of the the properties being transitioned in `inProgress`function such as:

```
$(...).animate({x: 100, inProgress: function(animatedValue, percentage){
    console.log(animatedValue.x, percentage);
}, fps: 24})

```

thanks a lot!

**Comment by baijunjie** [comment]
Animation is a "range of Transition" drive, not in the process of animation to create setTimeout () or setInterval ().If add this function, may make the animation performance than not using plug-in is low, because the calculation of Bessel curve of intermediate value performance overhead is huge.

**Comment by baijunjie** [comment]
Animation is a "CSS3 Transition" drive, not in the process of animation to create "setTimeout()" or "setInterval()".If add this function, may make the animation performance than not using plug-in is low, because the calculation of Bessel curve of intermediate value performance overhead is huge.

**Comment by alex00zoe** [comment]
Great. then can we use a 'parallel' `setInterval` function to enable an `inProgress` function with less functionality such as 

`inProgress: function(percentage){  }`

during the animation process?

the key functionality here is that when `stop()` or `finish()` method is called, `inProgress` will not be called any more. since a user of the library could determine the duration of the animation process however cannot explicitly determine the time when `stop()` or `finish()` is called.

**Comment by baijunjie** [comment]
You can use  "$.fn" to rewrite a "stop ()"

```
var _stop = $.fn.stop;
$.fn.stop = function() {
    ...
    _stop.apply(this, arguments)
}
```

**Comment by alex00zoe** [comment]
@baijunjie thanks a lot~
