### ISSUE TITLE
Doesn't read initial CSS Transform value correctly (maybe other properties are affected too.)

### ISSUE THREAD

**Issue by KingSora** [baijunjie/jquery.animate#6]
Hello!

There is a issue with the css hook. If you specify in CSS your transform: "transform: translate(100%, 0)" and then read it "$().css('x')" it will write "0" but it should be "100%". If you set the value in JS the value is read correctly. Because of this issue animations doesnt work properly if you have such rules in your CSS.

Reproduction: https://jsfiddle.net/jfkrhz67/
(Please read the console.)

Please try your best to fix this as fast as possible :)

Best regards,
Sora

**Comment by baijunjie** [comment]
Yes, only read the plugin Settings "CSS Transform value", can't read the stylesheet set "CSS Transform value"
