### ISSUE TITLE
Styles arent cleared in SlideDown if div is already slidedDown.

### ISSUE THREAD

**Issue by KingSora** [baijunjie/jquery.animate#7]
Hello!

There is a issue with the "SlideDown" function. In the original JQuery behavior all styles get cleared after the animation has finished. In your Plugin the styles are still applied.

Original: https://jsfiddle.net/jfkrhz67/3/
Plugin: https://jsfiddle.net/jfkrhz67/4/
(check the console output)

I figured out this happens only if the target div is already slidedDown if you call the function. If you call "slideUp(0)" before, this bug doesnt seems to appear.

Please fix this anyway for the same behaviors between your plugin and original jquery.

Best regards,
Sora

**Comment by baijunjie** [comment]
Ok, update v1.7.2
