### ISSUE TITLE
Incorrect size calculation with "toggle" and "show" values

### ISSUE THREAD

**Issue by KingSora** [baijunjie/jquery.animate#8]
Hello!

Your height calculation of the height which shall be applied on a "toggle" command (e.g. slideToggle) is slightly incorrect. You have to apply "display: block; overflow: hidden" style before you actually calculate the value.

I've fixed that like this in line 945:

old:
```javascript
var inlineStyleValue = $self[0].style[p],
	originalValue = $self.css(p, '').css(p);
$self.css(p, inlineStyleValue);
```

new:
```javascript
var isBox = (p === 'height' || p === 'width');
var inlineStyleValue = $self[0].style[p];
if(isBox)
	$self.css({ 'overflow' : 'hidden', 'display' : 'block' });

var originalValue = $self.css(p, '').css(p);

if(isBox)
	$self.css({ 'overflow' : '', 'display' : '' });
$self.css(p, inlineStyleValue);
```

Best regards,
Sora

**Comment by KingSora** [comment]
Whops, just realized I am dumb... 
My "fix" which I've posted would override the inline display and overflow style.
I've fixed that below.

```javascript
var isBox = (p === 'height' || p === 'width');
var inlineStyleValue = $self[0].style[p];
var inlineStyleOverflow, inlineStyleDisplay;
if(isBox) {
	inlineStyleOverflow = $self[0].style['overflow'];
	inlineStyleDisplay = $self[0].style['display'];
	$self.css({ 'overflow' : 'hidden', 'display' : 'block' });
}

var originalValue = $self.css(p, '').css(p);

if(isBox) {
	$self.css({ 'overflow' : inlineStyleOverflow, 'display' : inlineStyleDisplay });
}
$self.css(p, inlineStyleValue);
```

**Comment by baijunjie** [comment]
Ha, is you.
But, I don't know why to do this?
```html
<style>
.elem {
    height: 100px;
}
</style>
```
```js
var $elem = $('.elem');
$elem.height('200px');

var originalHeight1 = $elem.css('height', '').css('height');

$elem.css({ 'overflow' : 'hidden', 'display' : 'block' });

var originalHeight2 = $elem.css('height', '').css('height');
```
If it is a block or inline-block element
```js
originalHeight1 == 100px;
originalHeight2 == 100px;
```
If it is a inline element
```js
originalHeight1 == 0px;
originalHeight2 == 100px;
```
However I think originalHeight1 more correctly.

**Comment by KingSora** [comment]
Yeah... its me again! :D

I had this measurement problem in one of my complexer projects.
I've reproduced my case in jsfiddle: https://jsfiddle.net/gvmjoLpL/

As you can see, originalHeight1 is simply not correct, because one block is exactly 30px tall and container3 has 3 blocks.

You can check the same behavior in the official jQuery source code: https://code.jquery.com/jquery-3.1.1.js
Line 6864

**Comment by baijunjie** [comment]
Yes, this is actually jQuery problem.
It is doing just that.
```html
<style>
.container3 {
    height: 100%;
    display: none;
}
</style>
```
```js
$('.container3').css({
	display: "block",
	position: "absolute"
})
$('.container3')[0].getBoundingClientRect().height;  //=> 780px == window.innerHeight
```

**Comment by KingSora** [comment]
Ok, but whats your suggestion to solve this problem?
In fact jQuery toggles my div correctly but your plugin does not because of this bug.

jQuery = https://jsfiddle.net/gvmjoLpL/1/
PluginCurrent = https://jsfiddle.net/gvmjoLpL/2/
PluginFixed = https://jsfiddle.net/gvmjoLpL/3/

**Comment by baijunjie** [comment]
The demo is very detailed,I fix the problem,Use the v1.8.4 version.

**Comment by KingSora** [comment]
Thanks! :)

**Comment by KingSora** [comment]
Actually, I've realised that your fix doesn't work correctly if you use "slideDown()" instead of "slideToggle()".
My fix still works.

CurrentFix: https://jsfiddle.net/gvmjoLpL/5/
MyFix: https://jsfiddle.net/gvmjoLpL/6/
jQuery: https://jsfiddle.net/gvmjoLpL/7/

**Comment by baijunjie** [comment]
Sorry,Before not rigorous,Use the v1.8.5 version.

**Comment by KingSora** [comment]
Thanks again :)
